xcodeproj 'planckMailiOS'

target "planckMailiOS" do
    pod 'DateTools', '1.4.3'
    pod 'MBProgressHUD'
    pod 'UIActionSheet+Blocks'
    pod 'InboxKit'
    pod 'AFNetworking'
    pod 'UIAlertView+Blocks'
    pod 'SWTableViewCell', '~> 0.3.7'
    pod 'JTCalendar'
    
end

